### ISSUE TITLE
CODE ERROR

### ISSUE THREAD

**Issue by bruceleeks** [kashish-jain/Tambola#74]
i love using your site for the game but since 5 days, the website is currently giving the following error

Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by kashish-jain** [comment]
Hello,
Thanks for reaching out. We stopped maintaining the game for some time. But, we are back at it now. Game is back live now.
Again, really appreciate you reaching out. We'd love any feedback if you have.
